---
Name: eagerloading
Before:
  - 'mysite'
  - 'app'
After:
  - 'framework'
  - 'databaseconnectors'
---
SilverStripe\ORM\DataList:
  extensions:
    - Gurucomkz\EagerLoading\DataFilterEagerLoadingExtension
SilverStripe\ORM\DataObject:
  extensions:
    - Gurucomkz\EagerLoading\DataObjectExtension


SilverStripe\Admin\ModelAdmin:
  extensions:
    - Gurucomkz\EagerLoading\ModelAdminExtension
